Repository MAFIN-Squad/mafin-webui-selenium, pull requests merged in 2023-08, with the labels that each got.

#79 Add Screenshot utility
  Directory.Packages.props
  examples/Mafin.Web.UI.Selenium.Example/Mafin.Web.UI.Selenium.Example.csproj
  examples/Mafin.Web.UI.Selenium.YapomlExample/Mafin.Web.UI.Selenium.YapomlExample.csproj
  src/Mafin.Web.UI.Selenium/Enums/ScreenshotType.cs
  src/Mafin.Web.UI.Selenium/Mafin.Web.UI.Selenium.csproj
  src/Mafin.Web.UI.Selenium/Utilities/ScreenshotUtility.cs
  tests/Mafin.Web.UI.Selenium.Tests.Unit/Mafin.Web.UI.Selenium.Tests.Unit.csproj
  tests/Mafin.Web.UI.Selenium.Tests.Unit/Utilities/ScreenshotUtilityTests.cs
Labels: enhancement, .NET

#69 14 define json structure for configuration
  examples/Mafin.Web.UI.Selenium.Example/Core/WdmExtended.cs
  examples/Mafin.Web.UI.Selenium.Example/Mafin.Configuration.Chrome.json
  examples/Mafin.Web.UI.Selenium.Example/Mafin.Configuration.Edge.json
  examples/Mafin.Web.UI.Selenium.Example/Mafin.Configuration.Firefox.json
  examples/Mafin.Web.UI.Selenium.Example/Mafin.Configuration.Safari.json
  examples/Mafin.Web.UI.Selenium.Example/Mafin.Configuration.json
  examples/Mafin.Web.UI.Selenium.Example/Mafin.Web.UI.Selenium.Example.csproj
  examples/Mafin.Web.UI.Selenium.Example/Pages/ClientWorkPage.cs
  examples/Mafin.Web.UI.Selenium.Example/Tests/AbstractTest.cs
  examples/Mafin.Web.UI.Selenium.YapomlExample/AbstractTest.cs
  examples/Mafin.Web.UI.Selenium.YapomlExample/Mafin.Configuration.Chrome.json
  examples/Mafin.Web.UI.Selenium.YapomlExample/Mafin.Configuration.Edge.json
  examples/Mafin.Web.UI.Selenium.YapomlExample/Mafin.Configuration.Firefox.json
  examples/Mafin.Web.UI.Selenium.YapomlExample/Mafin.Configuration.Safari.json
  examples/Mafin.Web.UI.Selenium.YapomlExample/Mafin.Configuration.json
  examples/Mafin.Web.UI.Selenium.YapomlExample/Mafin.Web.UI.Selenium.YapomlExample.csproj
  src/Mafin.Web.UI.Selenium/Configuration/ConfigurationSectionAttribute.cs
  src/Mafin.Web.UI.Selenium/Configuration/WebConfigurationProvider.cs
  src/Mafin.Web.UI.Selenium/Driver/Strategy/AbstractDriverStrategy.cs
  src/Mafin.Web.UI.Selenium/Driver/Strategy/DriverMapping.cs
  src/Mafin.Web.UI.Selenium/Driver/Wdm.cs
  src/Mafin.Web.UI.Selenium/Mafin.Web.UI.Selenium.csproj
  src/Mafin.Web.UI.Selenium/Models/BrowserConfiguration.cs
  src/Mafin.Web.UI.Selenium/Models/TimeoutsConfig.cs
  src/Mafin.Web.UI.Selenium/Models/WebConfiguration.cs
  src/Mafin.Web.UI.Selenium/build/Mafin.Web.UI.Selenium.props
  tests/Mafin.Web.UI.Selenium.Tests.Unit/Driver/Strategy/DriverMappingTests.cs
Labels: enhancement

#89 Clean-up after updating from template
  Directory.Build.props
  Directory.Packages.props
  examples/Mafin.Web.UI.Selenium.Example/Core/BaseWebPage.cs
  examples/Mafin.Web.UI.Selenium.Example/Mafin.Web.UI.Selenium.Example.csproj
  examples/Mafin.Web.UI.Selenium.Example/Pages/ContactUsPage.cs
  examples/Mafin.Web.UI.Selenium.Example/Steps/ActionsSteps.cs
  examples/Mafin.Web.UI.Selenium.Example/Tests/FiltersTests.cs
  examples/Mafin.Web.UI.Selenium.Example/Tests/SearchTests.cs
  examples/Mafin.Web.UI.Selenium.YapomlExample/Mafin.Configuration.Edge.json
  examples/Mafin.Web.UI.Selenium.YapomlExample/Mafin.Configuration.Firefox.json
  examples/Mafin.Web.UI.Selenium.YapomlExample/Mafin.Configuration.Safari.json
  examples/Mafin.Web.UI.Selenium.YapomlExample/Mafin.Web.UI.Selenium.YapomlExample.csproj
  examples/Mafin.Web.UI.Selenium.YapomlExample/Pages/Base.page.cs
  examples/Mafin.Web.UI.Selenium.YapomlExample/Pages/_Components/Checkbox.component.cs
  examples/Mafin.Web.UI.Selenium.YapomlExample/Pages/_Components/MultiSelectionCombobox.component.cs
  examples/Mafin.Web.UI.Selenium.YapomlExample/Pages/_Components/MultiSelectionFilterList.component.cs
  examples/Mafin.Web.UI.Selenium.YapomlExample/Pages/_Components/SingleSelectionCombobox.component.cs
  examples/Mafin.Web.UI.Selenium.YapomlExample/Pages/_Components/SingleSelectionWithGroupsCombobox.component.cs
  src/Mafin.Web.UI.Selenium/Driver/Strategy/AbstractDriverStrategy.cs
  src/Mafin.Web.UI.Selenium/Mafin.Web.UI.Selenium.csproj
  tests/Mafin.Web.UI.Selenium.Tests.Unit/Mafin.Web.UI.Selenium.Tests.Unit.csproj
Labels: dependencies
